### PR TITLE
merge source comments; ignore private functions

### PR DESCRIPTION
**Pull request by rick-kilgore**
Merge comments found in the source file with those generated by
    smartcomments - give preference to the source file's comments where
    there are collisions

Provide an option in the config file to ignore private functions
    (any function with a name that starts with '_').  Private functions
    are ignored by default.

rename bin/index.js to bin/smartcomments

### CODE REVIEW

**Comment by darielnoel** [comment]
Hello Mr. Kilgore, thanks a lot for colaborating with SmartComments. The merge feature is one of the most important to SmartComments. Many people has written Us asking for this feature but unfortunately, We haven't had time to do it.

We've been reviewing and testing your Pull Request, and We believe that you has performed a great job,We want to merge your work it as soon as posible. But first we need clarify some issues.

**First Issue**

When We use your merge feature, if there are any collisions preference to the old source code comments is given. Instead off the new ones.
The consequences off this behavior are that for example:

If we change the name of a function, them When we generate new comments there will remain the old ones. So, the comments will not match with the present code.

On this matter, We could do two things:

```
1 - We give the preference to the new generated comments.
2 - We put a configuration option so the user could choice what to do. 
```

**Second Issue**

The tags that may be non value, (for example @return), are duplicated when merge is done. In this review we find out that this is cause by Regex _/@\w+\s+[^\r\n]+/_ used in "removeDuplicateTag" method.

A posible solution could be /@\w+\s+[^\r\n]/\* .

**Third Issue**

In the **mergeWithExistingComments** function you remove 'Description' comment line, which overwrites a configuration option behavior. If an user has defined by default that the description of his functions is (_This function have not, description_), when the comments are generated by the first time then nothing will appears on it.

**Four Issue**

The smartComment variable

``` javascript
//@param {object} smartComment - the smartcomments comment to match in the source. 
```

May have, a not very intuitive name, which can generate some confusions. We suggest change it for one of this options:

``` javascript
commentListItem

smartCommentItem

smartCommentsListItem 
```

**Five Issue**

We suggest you to use a "Single var Pattern" to declare the variables, cause this helps to reduce the download time.

``` javascript
   // "Single var Pattern" 
    var srcComment = smartComment.srcComment,
        mergedCommentLines = [ ];

    // Not
    var srcComment = smartComment.srcComment;
    var mergedCommentLines = [ ];
```

Please review this small issues, because it would be very useful for us. If you can not do that for any reason, please tell us, so we start working on it.
Thanks a lot again for your hard work. If we can help you in any matter please let us know.

Best Regards, Dariel.

**Comment by rick-kilgore** [comment]
Hi Dariel,

I'm glad to hear my updates might be useful to others :).

I've made some changes this evening that I think address most of your comments.  I'm still testing them, but expect to be able to update the PR some time tomorrow - probably after hours.

   Cheers,
    - Rick

**Comment by rick-kilgore** [comment]
Hi Dariel,

I've added changes that I think address most of your comments.  I made two deviations from your suggestions that I'm submitting for your consideration.  On your first issue, instead of blindly giving preference to the new comments in every respect, I tried to add intelligence to the logic - I wrote some logic to ensure that the resulting comment always has all the right parameter names, and only the right parameter names, and I use the generated comment tag for @method.

Second, I had trouble understanding the variable names you suggested in your issue four, so I tried going with generatedComment.  Does that work?

Oh, and I almost forgot, I didn't see the problem you were talking about with tags that don't have a value, but I think that the new regular expression I'm using in my new function parseTagNameValue() will address it.  But I can't confirm that it fixes the problem you saw, because I don't know how to reproduce it.

```
- Rick
```

**Comment by darielnoel** [comment]
Hi Rick, About the first issue, add intelligence to the logic is a good way to solve it. 
I am agree with this point. Just a little detail, you need to add the new generated @ return tag to the **mergedCommentLines** the same as you That makes with @ method tag. Because We Could lost values ​​@ return the new tags. 

The generatedComment it's a good variable name. 

The second issue was solved, with your new regular expression. 

Arranging the small detail that commented with respect to the first issue, I think your Pull Request may be ready to be mixed in the appropriate branch to version 0.3.0. That should come out sooner, not later than the weekend. 

Thank you very much again for your great help, I hope we can continue working together in the near future, You Already part of the team. That is our link https://trello.com/b/MqGkF1t0/node-js-app Trello board. There is still much work to do, and unfortunately we have very little time.

Best Regards, Dariel

**Comment by rick-kilgore** [comment]
I added a config option favor_generated.  When it's set to true (which is the default), it replaces whatever @return or @returns tag is in the source file with the generated one.

Thank you for creating this comment generator!  It really solves our problem of wanting to have good code discovery documentation without having to comment everything manually and having the comments inevitably get out of date over time.  We can now manually create comments only where they are merited (e.g., some tricky logic that needs explaining), and have this tool generate the rest!  Super valuable.

By the way, how we are using this is a use case that you might want to be aware of, in case others do the same.  I've set it up so that we put our minimal comments in the sources and commit them into source control that way.  Then, in our Gruntfile, to generate the docs I copy all the sources to a working dir, run smartcomments on them, and finally run yuidoc to generate the docs.  This happens every time we build and deploy our project.

**Comment by smartcomments** [comment]
+1

**Pull request merged**
